---
title: "An Illustration of Sharp RD: K&T 2017"
author: "Chi Huang"
date: "June 25, 2019"
output:
  word_document: default
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls()) #clear!

library(tidyverse)
library(rdrobust)
library(rddensity)
library(rdlocrand)


#################################
# Read data and define variables 
#################################

# Substitute with an appropriate work directory!
setwd("D:/User/Document/Service/計量方法研習營/2019/RD/RD designs/Cattaneo, Titiunik & Vazquez-Bare 2019 The RDD in Sage Handbook")

data <- read.csv("CTV_2019_Sage.csv")
tail(data)

Y <- data$mv_incpartyfor1
X <- data$mv_incparty

covs <- data[, c("pibpc", "population", "numpar_candidates_eff", "party_DEM_wonlag1_b1",  "party_PSDB_wonlag1_b1", "party_PT_wonlag1_b1", "party_PMDB_wonlag1_b1")]
covsnm <- c("GDP per capita", "Population", "No. Effective Parties", "DEM Victory t-1",  "PSDB Victory t-1", "PT Victory t-1", "PMDB Victory t-1")

glimpse(data)
```

## Scatter plot: often hard to see discontinuities
```{r}
ggplot(data, aes(X, Y))+geom_point()+geom_vline(aes(xintercept=0))+xlab("Incumbent Party's Margin of Victory at t")+
  ylab("Incumbent Party's Margin of Victory at t+1")
```

# Falsification analysis 

```{r}
# Analyze the density of the running variable
rddens <- rddensity(X)
summary(rddens)
rdplotdensity(rddens, X = data$mv_incparty[!is.na(data$mv_incparty)], 
              xlab = "Incumbent Party's Margin of Victory at t", ylab = "Estimated density")

# Test the effect of RD treatment on predetermined covariates
for(c in 1:ncol(covs)){
  summary(rdrobust(covs[,c],X))
  rdplot(covs[,c],X,y.label=covsnm[c],x.label="Incumbent Party's Margin of Victory",
         x.lim=c(-30,30),binselect = "qsmv")
}
```


# Outcome analysis 

# RD plot
```{r}
# rdplot

rdplot(Y,X,x.label="Incumbent Party's Margin of Victory at t",y.label="Incumbent Party's Margin of Victory at t+1")
```

# Continuity-based approach
```{r}
# without covariates

rdr <- rdrobust(Y,X)
summary(rdr)

# with covariates

rdrcovs <- rdrobust(Y,X,covs=covs)
summary(rdrcovs)

# Local randomization approach (not run)

# rdwin <- rdwinselect(X,covs,wmin=0.05,wstep=0.01,nwindows=200,seed=765,plot=TRUE)
# w <- 0.15

# rdrand <- rdrandinf(Y,X,wl=-w,wr=w,reps=1000,seed=765)

```
